### ISSUE TITLE
The type or namespace name `AndroidJavaProxy' could not be found. Are you missing a using directive or an assembly reference?

### ISSUE THREAD

**Issue by datomnurdin** [googlesamples/tango-examples-unity#10]
As per subject, i got this error when try to build and run the project. Even already import UnityEngine, the error message still occur.

http://docs.unity3d.com/ScriptReference/AndroidJavaProxy.html

```
Assets/TangoSDK/Core/Scripts/Common/AndroidLifecycle.cs(26,42): error CS0246: The type or namespace name `AndroidJavaProxy' could not be found. Are you missing a using directive or an assembly reference?
```

Code

```
public class AndroidLifecycleCallbacks : AndroidJavaProxy 
{
```

Please advice. Thank you.

**Comment by chaosemer** [comment]
This commonly happens if you mistakenly build for a platform other than Android.  Is that what happened here?
