### ISSUE TITLE
ExperimentalFloorFinding sample not working. 

### ISSUE THREAD

**Issue by TheOrestes** [googlesamples/tango-examples-unity#107]
This one sample am extremely keen on trying, however, base sample provided here does not work on Asus ZenFone AR. Unfortunately, I do not have any other device to try on. 
![screenshot_20170814-183228](https://user-images.githubusercontent.com/5098227/29273479-0a1441d2-8122-11e7-9a87-402bf3437417.jpg)

All I get is attached screenshot. Any idea what could be happening? Am totally new to tango dev.

**Comment by LudwikJaniuk** [comment]
Are you launching this in the Unity editor? Do you get something in the console, or adb logs? What version of Unity are you using?

**Comment by TheOrestes** [comment]
Launching this from a device. Am using Unity 5.6.0f3. Will provide adb log in sometime.

**Comment by TheOrestes** [comment]
Ok, this may sound odd but I restarted my phone & now the sample seems to be working fine. Am pulling my hairs on this for past day or two & solution was to restart my device. :)

**Comment by LudwikJaniuk** [comment]
Yeah crazy stuff happens sometimes. Good that it worked out for you.
