### ISSUE TITLE
PointCloud not found

### ISSUE THREAD

**Issue by datomnurdin** [googlesamples/tango-examples-unity#13]
I try to create a simple project for depth perception, unfortunately PointCloud not found inside component.

![screen shot 2015-06-01 at 11 13 01 am](https://cloud.githubusercontent.com/assets/5416242/7905649/75373edc-084e-11e5-980f-154d9e11d283.png)

Please advice. Thank you.

Reference
https://developers.google.com/project-tango/apis/unity/unity-depth-perception

![screen shot 2015-06-01 at 11 11 07 am](https://cloud.githubusercontent.com/assets/5416242/7905635/3ad44ab4-084e-11e5-9914-7d5aeb33c762.png)

**Comment by jguomoto** [comment]
The document is for an old version of sample code, you could check out the code from the [PointCloudUnity](https://github.com/googlesamples/tango-examples-unity/tree/master/PointCloudUnity) project to see how to take pointcloud data.

**Comment by jguomoto** [comment]
And the link is appears to be a outdate link, we've removed it from the nav-bar on our developer site. We will update this page once we updated the code and content. Could you also let us know where did you find this link? so we could remove or update the link.

**Comment by datomnurdin** [comment]
Sure. Thank you.
