### ISSUE TITLE
Voxel Tree Branch Removal

### ISSUE THREAD

**Issue by NVentimiglia** [googlesamples/tango-examples-unity#17]
In an effort to better understand mesh generation I have been going over the meshbuilder code. I think I may have found a minor bug. I have not replicated this in unity, but, I do have a console application where I am replicating / testing the logical internals.

https://github.com/googlesamples/tango-examples-unity/blob/master/ExperimentalProjects/MeshBuilder/Assets/Scripts/Voxel.cs#L113

```
            } else if(parent.leftTree == this) {
                //point parent directly at child
                parent.leftTree = (leftTree != null) ? leftTree : rightTree;
            } else if(parent.rightTree == this) {
                //point parent directly at child. **Bug Here**
                parent.rightTree = (leftTree != null) ? leftTree : rightTree;
            }
            return true;
        }
```

If the node has a right child the child may get pruned unexpectedly. Here is a fixed version.

```
                else if (ReferenceEquals(parent.Left, this))
                {
                    // Delete Leaf Node
                    parent.Left = Left ?? Right;
                }
                else if (ReferenceEquals(parent.Right, this))
                {
                    // Delete Leaf Node
                    parent.Right = Right ?? Left;
                }
```

To demo this error take the following tree :

```
C10
- L5
- - L4
- - - L3
- - R8
- - - L6
- - - R9
- R15
- - L14
- - - L12
- - R21
- - - L18
- - - - L16
- - - - R20
- - - R22
- - - - R24

```

If we delete R21, we will loose R24

```
C10
- L5
- - L4
- - - L3
- - R8
- - - L6
- - - R9
- R15
- - L14
- - - L12
- - R22
- - - L18
- - - - L16
- - - - R20

```

With my fix you get this output. Note the position of R24

```
C10
- L5
- - L4
- - - L3
- - R8
- - - L6
- - - R9
- R15
- - L14
- - - L12
- - R22
- - - L18
- - - - L16
- - - - R20
- - - R24

```

Let me know if you need help replicating this on your end.

**Comment by chaosemer** [comment]
Thanks for the bug report! Now that we have replaced the mesh building with a 3D reconstruction library, this is no longer an issue.

**Comment by NVentimiglia** [comment]
Thanks !
