### ISSUE TITLE
public void Insert(Voxel voxel, int hashkey) hides voxel field on line 42

### ISSUE THREAD

**Issue by NVentimiglia** [googlesamples/tango-examples-unity#19]
https://github.com/googlesamples/tango-examples-unity/blob/master/ExperimentalProjects/MeshBuilder/Assets/Scripts/Voxel.cs#L129

https://github.com/googlesamples/tango-examples-unity/blob/master/ExperimentalProjects/MeshBuilder/Assets/Scripts/Voxel.cs#L42

the variable 'voxel' on line 129 hides the variable voxel on line 42. Consider renaming the variable field on line 42 to _voxel or myVoxel or something.

**Comment by chaosemer** [comment]
Thanks for the bug report. Now that we are using the 3D reconstruction library, this is no longer an issue.
