### ISSUE TITLE
PoseController.cs resets camera pose to identity

### ISSUE THREAD

**Issue by silverandrew** [googlesamples/tango-examples-unity#2]
At https://github.com/googlesamples/tango-examples-unity/blob/master/MotionTrackingUnity/Assets/Scripts/PoseController.cs, the camera transform is always reset to Identity no matter what the camera transform is set to in Unity beforehand. The original SampleController.cs script in older versions of Unity used the existing pose set in Unity. Could this be changed to work the same way?

**Comment by chaosemer** [comment]
I believe the new DeltaPoseController will satisfy this use case.  It updates itself based on the delta between two positions instead of paying attention to the absolute position.
