### ISSUE TITLE
AreaLearning Sample Empty Scene 

### ISSUE THREAD

**Issue by arca1n-zz** [googlesamples/tango-examples-unity#21]
The area learning sample has an empty scene. Is that intentional? The sample as-is builds but is stuck at "powered by unity" screen as there is no camera or anything else to initialize in the level.

**Comment by jguomoto** [comment]
@arca1n are you using Unity 4.x or Unity 5.0.0? We noticed that these version of Unity cannot open the scene created in higher version.
