### ISSUE TITLE
Schur release - plugin in main SDK missing files

### ISSUE THREAD

**Issue by yosun** [googlesamples/tango-examples-unity#25]
This is an issue with the barebones Unity plugin included in the main release, and not with the tango examples. 

Assets/TangoSDK/Core/Scripts/Common/EventController.cs(48,39): error CS0117: `AndroidHelper' does not contain a definition for`ParseTangoEvent'

Easy steps to get the error yourself: 
1) Schur Tango Unity plugin @ https://developers.google.com/project-tango/downloads 
2) Import into Unity 5.1.2 
3) look in console for the import error above

**Comment by chaosemer** [comment]
Are you still having issues on the later releases?
