### ISSUE TITLE
Non-static method "Lcom/projecttango/unityuxhelper/TangoUnityUxHelper;

### ISSUE THREAD

**Issue by dcorbatta** [googlesamples/tango-examples-unity#29]
Most of the time, the Unity SDK call to a native method during the connecting UX screen. The method is not found and the connecting screen hang out.

```
I/Unity   ( 6065): AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lcom/projecttango/unityuxhelper/TangoUnityUxHelper;.䅣뿤(I)V"
I/Unity   ( 6065):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.Object[] args, Boolean isStatic) [0x00000] in <filename unknown>:0 
I/Unity   ( 6065):   at Un
```

The problem is with the method:
`tangoUxObject.Call("processPoseDataStatus", poseStatus);` 
But sometime it works.

My tango manager configuration is:
![screen shot 2015-09-14 at 6 01 44 pm](https://cloud.githubusercontent.com/assets/5963627/9861756/bac2e6c2-5b0a-11e5-81ab-6d30a6ef8e72.png)

I also use the Tango Point Cloud Prefab.

Unity version: 5.1.0f3 Personal
Tango Unity SDK: von Mises

**Comment by ZetaSMB** [comment]
I am having that exception too! Could be a mistake in the way that the signature method name is built??

**Comment by yosun** [comment]
Same issue with Weyl 5.2.1

**Comment by dcorbatta** [comment]
The only solution that I found was make a wrapper of the Tango Unity UX Helper in C. It's an issue with the Unity Android helpers. It sometime make a wrong signature of the inferred method. 
We are planning to share the code if it isn't fixed soon.

**Comment by patrick-marxent** [comment]
@dcorbatta did you end up finding a fix for this issue

**Comment by chaosemer** [comment]
This has been fixed a while ago, but we neglected to close this issue. Feel free to reopen if you're still have the problem.
