### ISSUE TITLE
AreaLearning saving Failed 

### ISSUE THREAD

**Issue by virtualman83** [googlesamples/tango-examples-unity#36]
Hi, 
The tracking work very well, I try to save my area into the system , and it is always failed.

adb on terminal shows this error :
I/Unity   (14202): Could not save area description.
I/Unity   (14202):    at System.Environment.get_StackTrace()
I/Unity   (14202):    at Tango.AreaDescription.SaveCurrent()
I/Unity   (14202):    at SaveADFController.KeyBoardBehaviour()
I/Unity   (14202):    at SaveADFController.OnGUI()

I use unity 5 under Mac .

is there any solution please 

Thanks

**Comment by chaosemer** [comment]
This can happen if you have not properly enabled Area Learning in your project.  Please check if you have "Area Learning" enabled on your Tango Manager object.

If this doesn't resolve your issue, the adb logcat from before what you posted will be helpful in diagnosing the issue.

**Comment by virtualman83** [comment]
Thanks for the answer , but it's enabled , and here is the logcat before :

(Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): TangoApplication.Initialize() Tango was initialized!
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): GetAreaDescription return value is: 0
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- date_ms_since_epoch: ����P
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- id: 3d109c70-5387-4dca-aab7-04d32348cacc
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- name: unnamed
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- transformation: 
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): GetAreaDescription return value is: 0
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- date_ms_since_epoch: �
I/Unity   (14585): ��P
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- id: 5a712ce6-1e1a-4a4f-9159-bb2714b1adab
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- name: bureau inge
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Key Values are- transformation: 
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): Area Learning is enabled.
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): PoseProvider.SetCallback() OnPose callback was set!
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): TangoEvents.SetCallback() Callback was set!
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): TangoApplication.ConnectToService()
I/Unity   (14585):  
I/Unity   (14585): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   (14585): 
I/Unity   (14585): TangoApplication.Connect() Tango client connected to service!

**Comment by chaosemer** [comment]
That looks like just the Unity messages.  There are messages with more detail printed out from the underlying Project Tango service.  You can get the full messages by running "adb logcat -d" with no other arguments.

**Comment by virtualman83** [comment]
Hi , 

Ok, here you have all the logcat -d data : 
 I/Unity   ( 1839):  
I/Unity   ( 1839): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   ( 1839): 
W/tango   (  185): tango-service-application.cc:1141 Stopping sensors...
I/tango   (  185): sensor-graph.cc:993 Stop requested.
D/SystemEventReceiver( 1469): Received GSERVICES_CHANGED broadcast
I/OcrUtils( 1469): Updating ocr activity enabled=false
I/DownloadManager( 1281): Download 151 finished with status SUCCESS
W/ActivityManager(  895): Unable to start service Intent { cmp=com.google.android.gms/.measurement.service.b } U=0: not found
I/CheckinService( 1469): Checkin interval check for package: unspecified last checkin: 1446624804027 min interval config: 0 actual interval: 8264
I/SystemUpdateService( 1469): receiver: Intent { act=com.google.gservices.intent.action.GSERVICES_CHANGED flg=0x10 cmp=com.google.android.gms/.update.SystemUpdateService$Receiver }
D/SystemUpdateService( 1469): onCreate
I/CheckinService( 1469): Checking schedule, now: 1446624812322 next: 1446664772985
I/CheckinService( 1469): active receiver: disabled
W/SQLiteConnectionPool( 1469): A SQLiteConnection object for database '/data/data/com.google.android.gms/databases/networkstatistics.sqlite' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
D/SystemUpdateService( 1469): onStartCommand: intent: Intent { cmp=com.google.android.gms/.update.SystemUpdateService (has extras) }
D/OcrModelManager( 1469): Updating downloaded model state (gservices changed)
D/NvOsDebugPrintf(  169): routeResultFromCAM: WARNING: only 0 requests in flight on sensor 1, frame drops likely
I/SystemUpdateService( 1469): cancelUpdate (empty URL)
I/SystemUpdateService( 1469): active receiver: disabled
E/Sensors (  895): [nosae] setDelay: 200000000 sec
D/Sensors (  895): Writing packet 54 32 0C 04 40 0D 03 00 74 
D/GCM     ( 1433): GcmService start Intent { act=com.google.gservices.intent.action.GSERVICES_CHANGED flg=0x10 cmp=com.google.android.gms/.gcm.GcmService } com.google.gservices.intent.action.GSERVICES_CHANGED
I/GCoreUlr( 1191): Starting service, intent=Intent { act=com.google.android.location.reporting.ACTION_UPDATE_WORLD cmp=com.google.android.gms/com.google.android.location.reporting.service.DispatchingService (has extras) }, extras=Bundle[{receiverAction=com.google.gservices.intent.action.GSERVICES_CHANGED}]
E/Sensors (  895): [nosae] setDelay: 10000000 sec
D/Sensors (  895): Writing packet 54 32 0B 04 10 27 00 00 74 
I/GCoreUlr( 1191): DispatchingService.onCreate()
D/SystemUpdateService( 1469): onDestroy
E/Sensors (  895): [nosae] setDelay: 8000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 40 1F 00 00 74 
I/GservicesUpdateTask( 2515): Updating Gservices keys
D/NvOsDebugPrintf(  169): NvCamScaler_OutputThread-- (error 0x0)
D/GCM     ( 1433): GcmService start Intent { act=com.google.android.checkin.CHECKIN_COMPLETE flg=0x10 cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.checkin.CHECKIN_COMPLETE
I/GCoreUlr( 1191): WorldUpdater received intent Intent { act=com.google.android.location.reporting.ACTION_UPDATE_WORLD cmp=com.google.android.gms/com.google.android.location.reporting.service.DispatchingService (has extras) } with receiverAction com.google.gservices.intent.action.GSERVICES_CHANGED
D/NvOsDebugPrintf(  169): SensorBayer_SetPowerLevel 1
E/Sensors (  895): [nosae] setDelay: 8000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 40 1F 00 00 74 
I/tango   (  185): sensor-graph.cc:906 Sending last_published_feature_tracks_and_imu_timestamp NaN
W/tango   (  185): tango-service-application.cc:1143 Waiting for sensors to finish...
W/tango   (  185): tango-service-application.cc:1146 Waiting for sparse mapping to finish processing...
W/tango   (  185): sparse-mapper.cc:584 SparseMapper: It's the end of days! timestamp = NaN
W/tango   (  185): sparse-mapper.cc:436 SparseMapper::ProcessAsync: got last timestamp: stop.
E/Sensors (  895): [nosae] setDelay: 200000000 sec
D/Sensors (  895): Writing packet 54 32 0B 04 40 0D 03 00 74 
I/Camera2ClientBase(  169): Closed Camera 1
W/GCM-DMM ( 1433): Force release of GOOGLE_C2DM lock
E/Sensors (  895): [nosae] setDelay: 20000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 20 4E 00 00 74 
I/GCoreUlr( 1191): WorldUpdater:com.google.gservices.intent.action.GSERVICES_CHANGED: Ensuring that reporting is stopped because of reasons: {account#-8#=[InactiveReason{mVersionCode=0, mIdentifier=6, mName='ReportingNotEnabled'}]}
W/tango   (  185): tango-service-application.cc:1157 Optimizing and saving map...
E/tango   (  185): map-manager-construction.cc:109 Not relocalized, cannot save map!
W/tango   (  185): tango-service-application.cc:1183 Save map call failed in learning mode. Either there has been a reset with no subsequent relocalization, or a map was loaded and has not yet been localized against.
I/tango_client_api(  185): Tango Service: saveAreaDescription, internal status -2
E/tango_client_api( 1839): TangoErrorType TangoService_saveAreaDescription(char (*)[37]): Internal Error: Could not save an area description. Is learning mode enabled?
W/art     (  163): Could not get current activity
I/ActivityManager(  895): Start proc android.process.acore for broadcast com.android.providers.contacts/.PackageIntentReceiver: pid=3128 uid=10003 gids={50003, 3003, 1028, 1015}
I/Unity   ( 1839): Could not save area description.
I/Unity   ( 1839):    at System.Environment.get_StackTrace()
I/Unity   ( 1839):    at Tango.AreaDescription.SaveCurrent()
I/Unity   ( 1839):    at SaveADFController.KeyBoardBehaviour()
I/Unity   ( 1839):    at SaveADFController.OnGUI()

**Comment by virtualman83** [comment]
Hi,

Here is the full logcat :

I/Unity   ( 3735): Before Saved
I/Unity   ( 3735):  
I/Unity   ( 3735): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   ( 3735): 
W/tango   (  185): tango-service-application.cc:1141 Stopping sensors...
I/tango   (  185): sensor-graph.cc:993 Stop requested.
I/Unity   ( 3735): NullReferenceException: Object reference not set to an instance of an object
I/Unity   ( 3735):   at SaveADFController.KeyBoardBehaviour () [0x00000] in <filename unknown>:0 
I/Unity   ( 3735):   at SaveADFController.OnGUI () [0x00000] in <filename unknown>:0 
I/Unity   ( 3735):  
I/Unity   ( 3735): (Filename:  Line: -1)
I/Unity   ( 3735): 
D/NvOsDebugPrintf(  169): routeResultFromCAM: WARNING: only 0 requests in flight on sensor 1, frame drops likely
E/Sensors (  895): [nosae] setDelay: 200000000 sec
D/Sensors (  895): Writing packet 54 32 0C 04 40 0D 03 00 74 
E/Sensors (  895): [nosae] setDelay: 10000000 sec
D/Sensors (  895): Writing packet 54 32 0B 04 10 27 00 00 74 
E/Sensors (  895): [nosae] setDelay: 8000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 40 1F 00 00 74 
D/NvOsDebugPrintf(  169): NvCamScaler_OutputThread-- (error 0x0)
D/NvOsDebugPrintf(  169): SensorBayer_SetPowerLevel 1
E/Sensors (  895): [nosae] setDelay: 8000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 40 1F 00 00 74 
I/tango   (  185): sensor-graph.cc:906 Sending last_published_feature_tracks_and_imu_timestamp NaN
W/tango   (  185): sparse-mapper.cc:584 SparseMapper: It's the end of days! timestamp = NaN
W/tango   (  185): sparse-mapper.cc:436 SparseMapper::ProcessAsync: got last timestamp: stop.
W/tango   (  185): tango-service-application.cc:1143 Waiting for sensors to finish...
W/tango   (  185): tango-service-application.cc:1146 Waiting for sparse mapping to finish processing...
E/Sensors (  895): [nosae] setDelay: 200000000 sec
D/Sensors (  895): Writing packet 54 32 0B 04 40 0D 03 00 74 
I/Camera2ClientBase(  169): Closed Camera 1
E/Sensors (  895): [nosae] setDelay: 20000000 sec
D/Sensors (  895): Writing packet 54 32 0A 04 20 4E 00 00 74 
W/tango   (  185): tango-service-application.cc:1157 Optimizing and saving map...
E/tango   (  185): map-manager-construction.cc:109 Not relocalized, cannot save map!
W/tango   (  185): tango-service-application.cc:1183 Save map call failed in learning mode. Either there has been a reset with no subsequent relocalization, or a map was loaded and has not yet been localized against.
I/tango_client_api(  185): Tango Service: saveAreaDescription, internal status -2
E/tango_client_api( 3735): TangoErrorType TangoService_saveAreaDescription(char (*)[37]): Internal Error: Could not save an area description. Is learning mode enabled?
I/Unity   ( 3735): PoseProvider.SaveAreaDescripton() Could not save area description with ID: 
I/Unity   ( 3735):  
I/Unity   ( 3735): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
I/Unity   ( 3735): 
I/Unity   ( 3735): After Save

Thanks a lot :)

**Comment by virtualman83** [comment]
I think this is the most important part : 
"Save map call failed in learning mode. Either there has been a reset with no subsequent relocalization, or a map was loaded and has not yet been localized against."

But I dont understand, what should I do ?

Thanks

**Comment by virtualman83** [comment]
Hi,

After some debugging , I found the error, but not the solution :
I/tango_client_api(  188): Tango Service: saveAreaDescription, internal status -2
E/tango_client_api( 4839): TangoErrorType TangoService_saveAreaDescription(char (*)[37]): Internal Error: Could not save an area description. Is learning mode enabled?

Any idea please :( 

Thanks

**Comment by chaosemer** [comment]
The key parts are here:

W/tango ( 185): tango-service-application.cc:1157 Optimizing and saving map...
E/tango ( 185): map-manager-construction.cc:109 Not relocalized, cannot save map!
W/tango ( 185): tango-service-application.cc:1183 Save map call failed in learning mode. Either there has been a reset with no subsequent relocalization, or a map was loaded and has not yet been localized against.

When loading an existing Area Description, you must get relocalized before saving will work.  You can detect that relocalization has happened because you will get a special pose update describing the start of service relative to the ADF.  In our AreaLearning sample, this changes the color of the trail rendered.

To relocalize, walk around the area previously learned after connected to the service.

**Comment by virtualman83** [comment]
Thank you, I understand the problem, but I've done what you've said , I walked around a lot of times , but the function IsLocalized return always false , and the trail is always blue ...  The same path is followed with the application tango explorer and the save works perfectly ... do you have any idea ?

Thanks a lot (sorry for my english)

**Comment by chaosemer** [comment]
The difference is probably that Tango Explorer was started creating a new Area Description, so it does not need to wait for localization.  The current Area Learning sample always tries to load the most recent Area Description with learning mode on, which needs to wait for localization.  The next release will have new Unity samples that enable choosing between both of these behaviors.

The best experience right now is to do all your Area Learning while creating a new Area Description and then relocalize to it with Learning Mode off.  Localization can take quite some time with Learning Mode on.  It is significantly faster to relocalize with Learning Mode off.  We are working to make this better.

**Comment by virtualman83** [comment]
Ok , thanks a lot :) Waiting for the new samples.
