### ISSUE TITLE
Persistent State Image Effect Errors

### ISSUE THREAD

**Issue by NVentimiglia** [googlesamples/tango-examples-unity#4]
Persistent State has the following errors.

Assets/Editor/Image Effects/CameraMotionBlurEditor.js(92,36): BCE0004: Ambiguous reference 'preview': CameraMotionBlurEditor.preview, UnityEditor.Editor.preview.

Assets/Editor/Image Effects/CameraMotionBlurEditor.js(93,9): BCE0004: Ambiguous reference 'preview': CameraMotionBlurEditor.preview, UnityEditor.Editor.preview.

The project is unchanged. Downloaded 5/7/2015

**Comment by NVentimiglia** [comment]
See my pull request above for a fix. I have signed the Google Contribution Agreement.

**Comment by jguomoto** [comment]
fixed in the M release.
