### ISSUE TITLE
VideoOverlayProvider.cs - m_emulationTexIdCaptureTextures does not exist

### ISSUE THREAD

**Issue by momo-the-monster** [googlesamples/tango-examples-unity#49]
I get this error when I open up the UnityProject from the latest SDK .unitypackage download (Okul) or when I open the UnityExamples project from this Github.

Indeed, the property "m_emulationTexIdCaptureTextures" does not exist in VideoOverlayProvider.cs, and that class does not extend another class so it seems like it's missing altogether.

**Comment by wederw** [comment]
Adding 
`private static YUVTexture m_emulationTexIdCaptureTextures;`
in `public class VideoOverlayProvider` seems to help.

**Comment by momo-the-monster** [comment]
@wederw - thanks, that allows a compile if VideoOverlayProvider never gets called, but it trips an error if it does, since m_emulationTexIdCaptureTextures is never allocated. 

I've tried allocating it on line 166 of VideoOverlayProvider.cs, but I only get static in my Unity Editor.

`m_emulationTexIdCaptureTextures = new YUVTexture(m_emulatedExpId_Y.width, m_emulatedExpId_Y.height, m_emulatedExpId_Y.width, m_emulatedExpId_Y.height, TextureFormat.RGBA32, false);`

**Comment by chaosemer** [comment]
I believe we fixed this a while back. Please reopen if this is still happening.
