### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Nicolas99-9** [googlesamples/tango-examples-unity#52]
I try to implement motion tracking but I have a bug.
When the tablet is too close to a wall, the app crash.

How to fix that ?

08-01 16:40:17.421 160-160/? I/DEBUG: pid: 8010, tid: 8010, name: my.app  >>> my.app <<<
08-01 16:40:17.889 912-8141/? W/ActivityManager:   Force finishing activity my.app/com.google.unity.GoogleUnityActivity
08-01 16:40:18.004 912-1034/? W/InputDispatcher: channel '656a8798 my.app/com.google.unity.GoogleUnityActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-01 16:40:18.004 912-1034/? E/InputDispatcher: channel '656a8798 my.app/com.google.unity.GoogleUnityActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-01 16:40:18.024 912-3584/? I/ActivityManager: Process my.app (pid 8010) has died.
08-01 16:40:18.036 912-1282/? W/InputDispatcher: Attempted to unregister already unregistered input channel '656a8798 my.app/com.google.unity.GoogleUnityActivity (server)'
08-01 16:40:18.036 912-1282/? I/WindowState: WIN DEATH: Window{656a8798 u0 my.app/com.google.unity.GoogleUnityActivity}
08-01 16:40:18.077 180-180/? D/phs:ipc-loc: Socket 11: hangup from client "my.app"

**Comment by Jiaxin-li** [comment]
had experienced the same problem

**Comment by pchuri** [comment]
I think that the exception ux of tango raise the crash. 
Have you try to disable `Draw Default UX Exception` of TangoManager?

Please refer to http://stackoverflow.com/questions/37791902/project-tango-unity-samples-crash/39657497#39657497.

**Comment by chaosemer** [comment]
Is this on the tablet dev kit or the Phab2 Pro?

**Comment by Nicolas99-9** [comment]
On the tablet kit dev

**Comment by chaosemer** [comment]
Thanks! I've added this to our internal bug tracker. As a workaround you can disable Draw Default UX Exceptions in your Unity project.
