### ISSUE TITLE
How to add Tango AR Camera in TangoWithMultiplayer?

### ISSUE THREAD

**Issue by xue-fei** [googlesamples/tango-examples-unity#53]
When recognize an area description,then Open Tango AR Camera,I want do this,What should I do?

That, I add a Tango AR Camera in MultiplayerCubeStacker scene,but Tips:

 "TangoApplication has area descriptions enabled ,but use area description pose option is not selected.
if left as-is ,this script will use the start of service pose even if an area description is loaded and/or area learning is enabled."

And auto-connect does not supply a chance to specify an Area Description.
Why ?

**Comment by chaosemer** [comment]
If you want to use Area Descriptions so two players can play in the same space, you will need to continue to keep Area Descriptions enabled. You should set "Use area descriptions pose" on the TangoARCamera prefab.

When using Area Descriptions, you need to specify which Area Description to use in a script call to Startup. The Multiplayer sample does that in [MulitplayerCubeStackerUIController](https://github.com/googlesamples/tango-examples-unity/blob/master/TangoWithMultiplayer/Assets/Scripts/MultiplayerCubeStackerUIController.cs#L203).
