### ISSUE TITLE
Re-installing Tango Core deletes ADFs

### ISSUE THREAD

**Issue by patrickjstefaniak** [googlesamples/tango-examples-unity#60]
Hi, I was experiencing issues running apps on my Tango so I uninstalled and re-updated Tango core, which worked, but then found that it had deleted all of my ADF files. To test , I created another ADF and re-installed core again and the same thing happened.

**Comment by chaosemer** [comment]
Fully uninstalling TangoCore will delete Area Descriptions, but that should not be possible since the system image comes with a TangoCore. Are you just reverting to the system image's TangoCore or are you somehow fully uninstalling TangoCore?

**Comment by chaosemer** [comment]
No replies in about a month, I'm assuming this is addressed. Please reopen if you still have this issue.
