### ISSUE TITLE
Huge motion-to-photon latency

### ISSUE THREAD

**Issue by ZeroLu** [googlesamples/tango-examples-unity#62]
I noticed a significantly huge motion-to-photon latency when using the cardboard example. It's actually also noticeable with a normal Tango app.  Motion-to-photon latency is  quite critical for a good VR experience. Do you have data on this? Do you have plans to decrease it? Can we as developers try to decrease it?

Thank you.

**Comment by chaosemer** [comment]
Motion to photon latency is extremely hardware specific. Devices like the Phab2 Pro and the Tango Development tablet do not have hardware optimized for small mo2pho. If you want a device optimized for VR, you should look for a device that is [Daydream Ready](https://vr.google.com/daydream/phones/). This is a different program than Tango.
