### ISSUE TITLE
Tango pose status is always VALID 

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#64]
'TangoPoseData.pose.status_code' is VALID after localization. But when I step out of the AreaDescription the status_code doesnot change, its still VALID. Ideally it should be INVALID.
I'm using AreaDescription & StartOfService as coordinate frames.

**Comment by chaosemer** [comment]
AreaDescriptions are used for localization. Once you are localized, you will continue to get VALID poses as long as you do not lose tracking.

See https://developers.google.com/tango/overview/area-learning for more details.

**Comment by imflash217** [comment]
What does 'loss of tracking' mean? 
After localization Tango Service will know where the Device is w.r.t to ADF and hence the pose status = VALID.
Once localized, if the device moves to an area which is not in the loaded ADF(used for localization) then Tango Service shouldn't know where the Device is as its no longer seeing a familier place and hence the pose status should be INVALID.

Please correct me if I'm getting it wrong.

**Comment by chaosemer** [comment]
Even if you are outside the Area Description, Tango can still track your device with very high precision so long as you have good features in the environment. This is how the pure odometry pipeline works without any area descriptions.

Tracking gets lost when there are no longer good features that can be seen. This can happen if you put the phone down on a table or in your pocket, or you turn of the lights. As long as the phone can see good features, the tracking will continue to work and the poses will come back VALID.

**Comment by ZYSHAQ** [comment]
chaosemer: https://plus.google.com/115403827738787951140/posts/L2KHThsfJ4E.
Please check this video. I lose tracking but tango pose stays as Valid (red text)

**Comment by imflash217** [comment]
@chaosemer 's answer is satisfying.
