### ISSUE TITLE
Camera doesn't rotate when tilting the device *android device have gyroscope

### ISSUE THREAD

**Issue by AliAkbarMontazeri** [googlesamples/tango-examples-unity#65]
I was build & run a simple scene to my Samsung GT-N7100 but the camera doesn't rotate when tilting the device. Any help ?

**Comment by andrewnakas** [comment]
The tango sdk only supports tango enabled phones. So at this time the tango tablet and lenovo phab 2 pro are the only supported devices. If your phone has a gyroscope you should be able to use the Google cardboard sdk.

**Comment by AliAkbarMontazeri** [comment]
Oh i didn't know that it only supports tango device for now. Thanks.
