### ISSUE TITLE
Screen capture apps DON'T run in Tango tablet. Asks for root.

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#72]
Screen capture applications doesnot run in Project Tango dev kit tablet.
They asks for root permmissions. I'm wondering if this is b'coz of Android SDK version it is running.
If so then how are Tango devs sharing screen in their demos.

**Comment by miraleung** [comment]
Have you considered Chromecasting? 

@jguomoto could you recommend other solutions?

**Comment by andrewnakas** [comment]
I thought people had trouble getting their tablet to chromecast, but it may be possible.  You also can wireless adb with poor resolution no sound, use corded adb with great resolution and no sound, or jailbreak the tango, install a screen recording app and  void your warranty, but I would think the warranty period is over anyway. but idk 

I've used the jailbreaking and corded adb with great success, and there are a couple posts buried on g+ that talk about wireless adb and jailbreaking the tablet.

**Comment by imflash217** [comment]
@miraleung No. I'haven't tried chromecasting. Let me give a try. Will update.

**Comment by jguomoto** [comment]
adb record is so far the best for offline recording. For realtime boardcasting, we usually use a gopro rig or USB-C to HDMI decoder.

**Comment by chaosemer** [comment]
adb screenrecord works well on both the DevKit tablet and the Phab2 Pro:
https://developer.android.com/studio/command-line/adb.html#screenrecord

**Comment by freshNfunky** [comment]
You can connect your Android Device with Android Studio.
Android studio allows to capture screenVideos.
It's an online Solution but works without any root hacking.
The only disadvantage ist you are connected via cable to the laptop.

**Comment by chaosemer** [comment]
I'm going to close this as solved. You've got a few answers that will all work here.
