### ISSUE TITLE
Video Overlay is Black

### ISSUE THREAD

**Issue by freshNfunky** [googlesamples/tango-examples-unity#73]
i Don't know when it happened exactly but either after:
- I upgraded Tango Developer Kit to current Updates via System Settings or...
- I Upgraded from Unity 5.3.5p7 to Unity 5.5.0p4
Deploying with Debug Symbols the tablet prompts the following message on the Android Monitor's logcat in Android Studio:

`01-25 21:31:13.001 537-558/com.xxxxxxxxx.unityexamples I/TangoEGL: checkAndUpdateEglState: invalid current EGLDisplay`

or

`01-25 21:32:09.688 537-558/com.xxxxxxxx.unityexamples I/TangoEGL: checkAndUpdateEglState: invalid current EGLDisplay
01-25 21:32:09.695 537-571/com.xxxxxxxx.unityexamples E/Unity: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 299)`

it's hard to track down where the error comes from exactly because the origin to this library is hard to track: ist it coming from the TangoManager or the EnvironmentLight texture. the message is Promted in SurfaceTexture.cpp and some environmentalLight - library
maybe there is also a Camera Permission Issue. But so far older Versions built with Unity 5.3.5 work just fine under this aspect without asking for a camera permission.
GL_INVALID_ENUM might be a reason of an incompatible VideoOverlay setting in the TangoManager

**Comment by chaosemer** [comment]
A few question about your project:
* Are you using multithreaded rendering?
* Are you using IL2CPP or Mono2x?

Thanks!

**Comment by freshNfunky** [comment]
whow, i think the multithreaded Option was the bad guy.
Now with multithreading turned off the camera image is back on :) :)

**Comment by chaosemer** [comment]
Glad to hear it! I'm glad your issue is fixed.
