### ISSUE TITLE
Area Description List Incomplete

### ISSUE THREAD

**Issue by freshNfunky** [googlesamples/tango-examples-unity#77]
I am havong another problem with the area descriptions. It's the same problem as postet on G+
but mentioned to be a Zenia core problem: https://plus.google.com/102908861368834422170/posts/LH6yEcVojxt

the List of the ADFs is incomplete. When debugging the app via Android Studio -> Android Monitor the app also prompts the error:
`02-07 19:47:13.954 7221-7243/? I/tango: file_io.cc:848 Successfully read ADF footer message from file: /data/data/com.google.tango/files/Tango/ADFs/c43b163b-e909-4da4-a9bb-beecf16f25f7
02-07 19:47:13.954 7221-12594/? I/tango_client_api: Tango Service: loadAreaDescriptionMetadata, internal status 0
02-07 19:47:13.963 7221-7243/? I/tango: file_io.cc:848 Successfully read ADF footer message from file: /data/data/com.google.tango/files/Tango/ADFs/f614ca98-c8c2-419b-ba17-cc7226b851c9
02-07 19:47:13.963 7221-13043/? I/tango_client_api: Tango Service: loadAreaDescriptionMetadata, internal status 0
02-07 19:47:13.974 7221-7243/? I/tango: file_io.cc:848 Successfully read ADF footer message from file: /data/data/com.google.tango/files/Tango/ADFs/f54cca4a-89b7-4710-b8aa-294e2d1d37a6
02-07 19:47:13.974 7221-8413/? I/tango_client_api: Tango Service: loadAreaDescriptionMetadata, internal status 0
02-07 19:47:13.980 7221-7243/? E/tango: file_io.cc:950 Failed to open ADF file: /data/data/com.google.tango/files/Tango/ADFs/758d24ef-695a-4999-bbb2-c243475dbbe9
02-07 19:47:13.980 7221-7236/? I/tango_client_api: Tango Service: loadAreaDescriptionMetadata, internal status -2
02-07 19:47:13.980 7221-7243/? E/tango: adf_metadata_utils.cc:167 Failed to load metadata. Unable to read ADF footer from: /data/data/com.google.tango/files/Tango/ADFs/758d24ef-695a-4999-bbb2-c243475dbbe9
02-07 19:47:13.980 7221-7243/? E/tango: tango_context.cc:436 Failed to load metadata. ADF not found with UUID: 758d24ef-695a-4999-bbb2-c243475dbbe9
02-07 19:47:13.985 15509-15528/com.felixschallercom.unityexamples I/Unity: Could not get metadata pointer for uuid 758d24ef-695a-4999-bbb2-c243475dbbe9.`

it's a bit odd because on some builds it works without error and in others the error appears again. The most stable Configuration with the Developer Kit is: Building with mono2x and Gradle. With the internal or IL2CPP it's so far permanent. I am building with Unity 5.5.0p4

**Comment by chaosemer** [comment]
This will happen only on the TangoCore on the DevKit tablet. An app that does not properly connect to the Tango Service will revert to the legacy service and will cause Area Descriptions to only be accessible to the legacy service. This was done to avoid breaking existing apps.

The legacy service is not available on the Phab2 Pro or future Tango devices.
