### ISSUE TITLE
Error: Incorrect Configuration while using Tango Explorer or any Tango enabled app (dalvik v/s ART)

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#78]
I'm **suddenly** getting this error while running any Tango enabled app (Google's Tango Explorer app etc..or my own build):
`Error: Incorrect Configuration. Please go to Settings-->Developer options and use ART`

By default the device came with `dalvik` & was running fine. 
I've read some [posts ](https://www.reddit.com/r/Android/comments/25qlut/psa_dont_use_the_art_runtime_and_expect_your/)pointing the issues with using `ART`.

Still I switched to 'ART' and after rebooting the tablet, all the apps that were installed before changing to ART works fine(tango capabilities) but if I install a new tango-enabled app its not able to access tango core and throws an error.

What should I do?

**Comment by small-potatoes** [comment]
Hi, can you provide information about the device and android version you are experiencing this issue?

**Comment by imflash217** [comment]
I am using Google Project Tango Development Kit Tablet running Kitkat.

**Comment by chaosemer** [comment]
Thanks for the info.

You should be aware that ART on Android 4.4 has a bug that causes all Unity apps to crash within 5 - 10 minutes. For that reason we suggest using Dalvik when developing Unity apps, despite the warning you see.  Please confirm if everything works again once you switch back.
