### ISSUE TITLE
meshbuilder example doesnt work?

### ISSUE THREAD

**Issue by sterlingcrispin** [googlesamples/tango-examples-unity#8]
Hey has anyone had luck getting the mesh builder example to run or had luck integrating it with another unity project? 

When I open the meshbuilder.unity scene its just a handful of scripts not connected to any game object, and when the project is compiled and launched on Tango it just crashes instantly

**Comment by jguomoto** [comment]
HI sterlingcrispin, are you using Unity 4 or Unity 5? All of the example project is Unity 5 based.

**Comment by sterlingcrispin** [comment]
hey I'm using Unity 5 - the project is totally empty

I can see here there's supposed to be an Empty Game Object with a few scripts attached in the scene
https://developers.google.com/project-tango/apis/unity/unity-meshing

What else is there supposed to be?

Should the Custom Point Cloud Listener script be attached to the camera? This script wants an Occupancy Manager Object but its unclear what that is

Could you provide a working copy of the project?

when the project opens: 
![screen shot 2015-05-27 at 12 02 21 pm](https://cloud.githubusercontent.com/assets/2976761/7844926/5f2cf5bc-0468-11e5-8081-b9be69a77c54.png)

when I open the only scene:
![screen shot 2015-05-27 at 12 02 31 pm](https://cloud.githubusercontent.com/assets/2976761/7844929/6730c1d0-0468-11e5-9812-1cff0c641e7d.png)

**Comment by r4ravi2008** [comment]
That is weird. I just opened the MeshBuilder scene in Unity. Here is the screenshot:
![screen shot 2015-06-03 at 12 57 37 pm 1](https://cloud.githubusercontent.com/assets/6422949/7970062/5b38027a-09f0-11e5-8f99-61aa4f2358fa.png)

For sanity check, my unity version is 5.0.1f1

**Comment by NVentimiglia** [comment]
I ran into this issue with Unity5 when I would submit (other) packages in the asset store. The packages were fine on my end, but people complained about empty scenes. After I resubmitted my package the complaints went away.

**Comment by jguomoto** [comment]
We find a issue between Unity 5.0.2 scene cannot be opened in Unity 5.0.0 version, it will appear as an empty scene. I think that might be the case of this issue.
