### ISSUE TITLE
ExperimentalMeshOcclusion is not working

### ISSUE THREAD

**Issue by SquareLi** [googlesamples/tango-examples-unity#87]
The occlusion does not work for me, I can still see the virtual object (armarker) behind real world objects.

**Comment by chaosemer** [comment]
Hi! Unfortunately, recent versions of Unity have changed the way the depth buffer got captured. For this to work, you need to run on Unity 5.2.

**Comment by SquareLi** [comment]
Thanks @chaosemer. I built the example on Unity 5.2, and the example keeps crashing on my Tango.

**Comment by LudwikJaniuk** [comment]
Using some other workarounds, I got something similar working on Unity 5.6. If anyone's still interested, I can detail how I got it working.
