### ISSUE TITLE
ExperimentalMeshOcclusion is not working

### ISSUE THREAD

**Issue by SquareLi** [googlesamples/tango-examples-unity#88]
Because #87  is closed, I am opening a new ticket here because the example built on Unity 5.2 is crashing on my Tango.

The error I got is "Channel is unrecoverably broken and will be disposed!" and I did not see any code exception.

My Tango's model is NX-74751 Development kit.

Android Version is 4.4.2

**Comment by bopangzz** [comment]
Can you attach the a full logcat? I cannot reproduce the crash on Unity 5.2.

**Comment by chaosemer** [comment]
If you are still having this issue, please reopen.
