### ISSUE TITLE
Exception thrown in TangoSetupTeardownManager

### ISSUE THREAD

**Issue by codec-abc** [googlesamples/tango-examples-unity#89]
Hi,

I have an exception being throw when using video overlay in TangoSetupTeardownManager because its member `m_yuvTexture`  is null. This cause seems to be that the initialization order is wrong. As we can see [here](https://github.com/googlesamples/tango-examples-unity/blob/master/UnityExamples/Assets/TangoSDK/Core/Scripts/TangoWrappers/TangoApplication.cs#L583) the texture is created after having created the [TangoSetupTeardownManager](https://github.com/googlesamples/tango-examples-unity/blob/master/UnityExamples/Assets/TangoSDK/Core/Scripts/TangoWrappers/TangoApplication.cs#L535). I think an easy fix is to set up the creation of the texture sooner in the code.

**Comment by small-potatoes** [comment]
Thanks for bringing this to our attention!  A fix has been crafted for our next release.
