### ISSUE TITLE
Can this library identify other project such as Human?

### ISSUE THREAD

**Issue by datomnurdin** [googlesamples/tango-examples-unity#9]
As per subject, is it possible? Or it has face recognition in real time?

**Comment by sterlingcrispin** [comment]
This library doesn't come with facial recognition but its possible to implement one

**Comment by datomnurdin** [comment]
Are you developer from Project Tango? I got one another question, how to identify who he/she is? Is it Sarah, John or Connor? How?

**Comment by sterlingcrispin** [comment]
I'm not a google employee, you should do a search for an online course about facial recognition or at least read its Wikipedia article, then find a suitable codebase. I'd recommend libccv or opencv. This is the wrong place

**Comment by NVentimiglia** [comment]
https://www.metaio.com/ has facial recognition for unity3d.

**Comment by sterlingcrispin** [comment]
Yeah but they just got bought and are shutting their service down, try http://artoolkit.org instead

**Comment by NVentimiglia** [comment]
@sterlingcrispin  Good to know.
