### ISSUE TITLE
how to use this project

### ISSUE THREAD

**Issue by feixiaku** [googlesamples/tango-examples-unity#91]
I develop tango AR app using Unity, I want to record the AR video, but I can't find a API to record video in the tango Android device, so I have to use Android API. in the Unity project, I import tango's unity SDK package, so, at Plugins/Android directory, there are a AndroidManifest.xml file and google_unity_wrapper.aar, If I want to use Android API, how to integrate my code into google_unity_wrapper.aar? or, how to use AndoridIntergration directory?

**Comment by chaosemer** [comment]
Hi feixiaku! There's no built in support for recording video in the SDK. There are multiple video recording plugins on the Asset Store, we've found all the ones we've investigated to work well.

**Comment by feixiaku** [comment]
could you give me a link or the name that you have used plugins' name, so i can use the same one, That's great, thank you

**Comment by chaosemer** [comment]
I've seen apps do well with Everyplay (https://www.assetstore.unity3d.com/en/#!/content/16005), and I would expect other video recording plugins to work well too.
