### ISSUE TITLE
Maybe this is not an issues,but in China,the phab2pro can't use google play store and the tango core in lenove store  is Low version. 

### ISSUE THREAD

**Issue by veyvin** [googlesamples/tango-examples-unity#93]
because of the low version tango core, so in the example,  it shows out of date. I have no way to download new version tango core, what can I do?

**Comment by chaosemer** [comment]
Thank you for your report!

We're working with Lenovo to get a TangoCore update onto the store. In the mean time, you can check "Allow out of date API" on the TangoApplication, though some features will not work in this case namely anything dealing with color image as bytes and color reconstruction.
