### ISSUE TITLE
Export ADF file doesn't work - Unity-Tango SDK "AreaDescriptionManagement" example

### ISSUE THREAD

**Issue by antonin137** [googlesamples/tango-examples-unity#97]
Built application asks for exporting ADF file permissions and 
**areaDescription.ExportToFile(kb.text)** in script **ADMGUIController**
returns true, but no file is written on desired location (/sdcard/file.adf or any other internal like /storage/emulated/0/somefile.adf)... Using Unity 5.6.1 and Lenovo Phab 2 Pro, clean project with most recent Tango package imported. Anybody experienced similar isue ?

Is it possible to change ADF file storage to some accessible folder ?

Thank You

**Comment by martinbilello** [comment]
Hi, the parameter in that case should be a folder path and not a file. We are going to make sure this is clearer and change it so it returns false in this case.

Thanks

**Comment by antonin137** [comment]
Hi,
Tested enter only a path and it works! So, not an issue...
Thank You for fast response :-)
