### ISSUE TITLE
"Error : Failed to Connect to Tango Services" after updating to Hopak release in Unity

### ISSUE THREAD

**Issue by imflash217** [googlesamples/tango-examples-unity#98]
Hi @chaosemer ,
I'm getting this error "Failed to Connect to Tango Services" after updating to Hopak release in Unity.
I wonder if Hopak release is stable?
Same app used to work fantastic in previous releases.
I'm using Tango Development Kit.

Any help....please.

**Comment by pancymon** [comment]
Hi,

I've forwarded your message to @chaosemer, thanks for the report!

**Comment by chaosemer** [comment]
Unfortunately, the Tango development kit tablet is no longer supported by the latest SDK.

You can buy a Phab 2 Pro for further development or stick with an older SDK. You should not need to update the SDK to continue building Tango apps.

**Comment by imflash217** [comment]
Thanks.
